fun_facts = ['The scientific term for brain freeze is “sphenopalatine ganglioneuralgia”.', 
'Canadians say “sorry” so much that a law was passed in 2009 declaring that an apology can’t be used as evidence of admission to guilt.', 
'Back when dinosaurs existed, there used to be volcanoes that were erupting on the moon.', 
'The only letter that doesn’t appear on the periodic table is J.', 
'One habit of intelligent humans is being easily annoyed by people around them, but saying nothing in order to avoid a meaningless argument.', 
'If a Polar Bear and a Grizzly Bear mate, their offspring is called a “Pizzy Bear”.',
'In 2006, a Coca-Cola employee offered to sell Coca-Cola secrets to Pepsi. Pepsi responded by notifying Coca-Cola.',
'There were two AI chatbots created by Facebook to talk to each other, but they were shut down after they started communicating in a language they made for themselves.',
'A single strand of Spaghetti is called a “Spaghetto”.',
'Hershey’s Kisses are named that after the kissing sound the deposited chocolate makes as it falls from the machine on the conveyor belt.',
'Ithyphallophobia is the fear of erections',
'A tapir has the largest penis to body ratio of any animal',
'A duck and a rooster were the first passengers in a hot air balloon',
'Upon losing battles apes will tend to masturbate',
'Most lipstick contains fish scales']